#!/bin/sh
set -eu
umask 077
# Never start PostgreSQL or change an existing cluster. The operator supplies a NEW isolated parent.
: "${RESTORE_ISOLATED_ROOT:?new isolated restore parent required}"
: "${BACKUP_KEY_FILE:?private key required}"
[ "$#" -eq 1 ] || exit 64
case "$RESTORE_ISOLATED_ROOT" in /*) ;; *) exit 64;; esac
[ -d "$RESTORE_ISOLATED_ROOT" ] && [ ! -L "$RESTORE_ISOLATED_ROOT" ] || exit 64
[ ! -e "$RESTORE_ISOLATED_ROOT/pgdata" ] || exit 64
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
work=$(mktemp -d "$RESTORE_ISOLATED_ROOT/.restore.XXXXXXXX")
trap 'rm -rf -- "$work"' EXIT HUP INT TERM
node "$script_dir/../backup/crypto.mjs" verify "$1/base.enc" "$1/manifest.json"
node "$script_dir/../backup/crypto.mjs" decrypt "$1/base.enc" "$work/base.tar" "$BACKUP_KEY_FILE"
mkdir "$work/data"
# Backup was generated by our script from plain pg_basebackup. Extract in a private isolated directory.
tar -xf "$work/base.tar" -C "$work/data"
node "$script_dir/verify-restored.mjs" "$work/data" "$1/manifest.json"
rm "$work/data/echo_snapshot_at"
pg_verifybackup "$work/data" > "$work/verify.log" 2>&1 || { echo 'Restored PostgreSQL backup verification failed' >&2; exit 1; }
# Disable source archiving/network listener. No runtime is started by this preparation step.
cat > "$work/data/postgresql.auto.conf" <<'CONFIG'
archive_mode = 'off'
archive_command = ''
listen_addresses = ''
CONFIG
node "$script_dir/prepare-wal.mjs" "$work/data"
printf 'RESTORE_FENCE=on\n' > "$work/restore.env"
mv "$work/data" "$RESTORE_ISOLATED_ROOT/pgdata"
mv "$work/restore.env" "$RESTORE_ISOLATED_ROOT/restore.env"
echo 'Prepared isolated backup; fence all runtimes, start isolated DB, set database fence BEFORE any runtime, reconcile, verify, then explicitly reopen.'
